version: '3.3'
services:
  kycnot:
      ports:
          - '127.0.0.1:1337:1337'
      volumes:
          - './data:/app/data'
      container_name: kycnot
      image: pluja/kycnot
      restart: unless-stopped